#!/bin/bash

START=9
END=11

python3 sampling_run_slurm.py --train_file transformers_trainer.py --dataset conll --data_dir dataset/conll --suffix 25 --prompt max --template basic --pfrom "${START}" --pto "${END}"
