#!/bin/bash

START=21
END=23

python3 sampling_run_slurm.py --train_file transformers_trainer.py --dataset conll --data_dir dataset/conll --suffix 50 --prompt max --template basic --pfrom "${START}" --pto "${END}"
