#!/bin/bash

NODENAME=$(hostname)
START=13
END=15

srun --gres=gpu:1080:1 --nodelist "${NODENAME}" --time 1500 python3 sampling_run_slurm.py --train_file transformers_trainer.py --dataset conll --data_dir dataset/conll --suffix 25 --prompt max --template basic --pfrom "${START}" --pto "${END}"
